In [1]:
import numpy as np
data = list(range(12))  # 0..11
batch_size = 3
nbatch = len(data)//batch_size  # 4

# 方法 A（reshape+transpose）
data = np.array(data[:nbatch * batch_size])
A = data.reshape((batch_size,nbatch)).transpose()
A = np.ascontiguousarray(A)

# 方法 B（注释版逻辑）
B = np.zeros((nbatch, batch_size), dtype=A.dtype)
for i in range(nbatch):
    idx = [i + j*nbatch for j in range(batch_size)]
    B[i, :] = np.array(data)[idx]

assert np.array_equal(A, B)
print(A)
print(B)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
